---
title: "Assignment 6 Claire 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(sf)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)
```

```{r}
census_api_key("c1d01ba587d3b71212d6431e6568b69681f35baf", install=TRUE, overwrite=TRUE)

readRenviron("~/.Renviron")
```

# I'm interested in total owenr with (H017002) and the young owner population (H017D004)
```{r}
Suffolk_Youngowner <- get_decennial(geography = "block",
                          state = "MA", county = "Suffolk",
                          year = 2010,
                          output = "wide",
                          variables = c(tot_owner = 'H017002',
                                        young_owner = 'H017D004'),
                          geometry = TRUE)
```
```{r}
Suffolk_Youngowner <- Suffolk_Youngowner %>%
  mutate(pct_youngowner = young_owner / tot_owner) %>%
  filter(tot_owner > 0)
```

```{r}
MA_state_plane <- "+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000.0001016002 +y_0=750000 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

ggplot(Suffolk_Youngowner) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "stamenbw") +
  geom_sf(color = NA, aes(fill = pct_youngowner), alpha = 0.7) +
  coord_sf(crs = MA_state_plane) +
  scale_fill_continuous(low="cornsilk", high="darkgreen", 
                       na.value=NA,
                       name = "Percent of homeowners who are aged 25-34",
                       breaks = c(0,0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
                       labels = c("0", "10%", "20%", "30%", "40%", "50%", "60%", "70%", "80%", "90%" , "100%")) +
  theme_void() 


```


```{r}
MA_Youngowners_palette <- colorNumeric(c("cornsilk", "darkgreen"), Suffolk_Youngowner$pct_youngowner)

Youngowner_map1 <- leaflet(Suffolk_Youngowner) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(stroke = FALSE, fillOpacity = 0.7,
    color = ~MA_Youngowners_palette(pct_youngowner)) %>%
  addLegend("bottomright", pal = MA_Youngowners_palette, values = ~pct_youngowner,
    title = "Percent of home owners who are ages 24-35 ",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

Youngowner_map1
```
```{r}
png("youngowner_map1", width = 5, height = 3, units = "in", res = 300)
Youngowner_map1
dev.off()
```
```{r}
pdf("youngownerpdf", width = 5, height = 3)
Youngowner_map1
dev.off()
```


```{r}
Youngownermap <- leaflet(Suffolk_Youngowner) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~MA_Youngowners_palette(pct_youngowner), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "darkorange", fillOpacity = 0.9),
              label = Suffolk_Youngowner$NAME,
              popup = paste("Total homeowners: ", Suffolk_Youngowner$tot_owner, "<br/>",
                            "Owners aged 24-35: ", Suffolk_Youngowner$young_owner, " (", 
                            round(Suffolk_Youngowner$pct_youngowner * 100, 1), "%)", sep = "")) %>%
    addLegend("bottomright", pal = MA_Youngowners_palette, values = ~pct_youngowner,
    title = "Percent of home owners who are aged 24-35",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

Youngownermap
```
```{r}
saveWidget(Youngownermap, file="inter_youngowner.html")
```

```{r}
png("youngownerlabels.png", width = 5, height = 3, units = "in", res = 300)
Youngownermap
dev.off()
```

```{r}
acs_vars <- load_variables(2017, "acs5")
```


```{r}
transit_Suffolk <- get_acs(geography = "tract", county = "Suffolk", state = "MA", 
                           year = 2019, survey = "acs5",
                           variables = c(tot_wrkrs = "B08301_001", pt_wrkrs = "B08301_021"),
                           output = "wide", geometry = TRUE) 
```

```{r}
transit_Suffolk <- transit_Suffolk %>%
  select(-tot_wrkrsM, -pt_wrkrsM) %>%
  filter(tot_wrkrsE > 0) %>%
  mutate(pct_transit = round(100 * pt_wrkrsE / tot_wrkrsE, 1))
```

```{r}
transit_palette <- colorNumeric(c("green", "blue"),
                                transit_Suffolk$pct_transit)

transit_map <- leaflet(transit_Suffolk) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(fillColor = ~transit_palette(pct_transit), weight = 1, color = "gray", fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "yellow", fillOpacity = 0.9),
              label = transit_Suffolk$NAME,
              popup = paste("Total workers: ", transit_Suffolk$tot_wrkrsE, "<br/>",
                            "Work from home: ", transit_Suffolk$pt_wrkrsE, " (", 
                            transit_Suffolk$pct_transit, "%)", sep = "")) %>%
    addLegend("bottomright", pal = transit_palette, values = ~pct_transit,
    title = "Percent of workers<br/>work from home",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1)

transit_map
```

```{r}
MBTA_url <- feedlist[feedlist$t == "MBTA GTFS",]$url_d

MBTA <- read_gtfs(MBTA_url)

transit_stops <- MBTA$stops

transit_stations <- transit_stops %>%
  filter(location_type == 1)
```

```{r}
station_sf <- st_as_sf(transit_stations, 
                          coords = c("stop_lon", "stop_lat"), 
                          crs = "WGS84")
```

```{r}
st_write(station_sf, "MBTA_stations.csv", layer_options = "GEOMETRY=AS_XY", append = FALSE)

stations_2 <- read_csv("MBTA_stations.csv")
```

```{r}
transit_map2 <- transit_map %>%
  addMarkers(lng = transit_stations$stop_lon,
             lat = transit_stations$stop_lat,
             popup = transit_stations$stop_name)

transit_map2
```

```{r}
limits <- st_bbox(transit_Suffolk)

transit_map3 <- transit_map2 %>%
   fitBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) %>%
   setMaxBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) 

transit_map3
```

```{r}
transit_map4 <- transit_map %>%
  addCircleMarkers(stroke = FALSE, color = "pink", fillOpacity = 1, radius = 2,
                   lng = transit_stations$stop_lon,
                   lat = transit_stations$stop_lat,
                   popup = transit_stations$stop_name) %>%
   fitBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) %>%
   setMaxBounds( lng1 = as.numeric(limits[1]),
                lat1 = as.numeric(limits[2]),
                lng2 = as.numeric(limits[3]),
                lat2 = as.numeric(limits[4])) 

transit_map4
```

